import { fundsResult, normalizeOrigin, parseUsd, sanitizeText } from './policy.mjs';
const $ = id => document.getElementById(id);
let source = null, key = '', requests = [], current = null, preview = null, busy = false;
let generation = 0;
const BASE = 'http://127.0.0.1:8765/device/';

function message(text, error = false) {
  $('message').hidden = false;
  $('message').textContent = text;
  $('message').classList.toggle('error', error);
}
async function api(path, data) {
  if (!key) throw new Error('Pair the local broker first.');
  let response;
  try {
    response = await fetch(BASE + path, {
      method: data === undefined ? 'GET' : 'POST',
      headers: { Authorization: 'Bearer ' + key, 'Content-Type': 'application/json' },
      body: data === undefined ? undefined : JSON.stringify(data),
      credentials: 'omit', redirect: 'error', cache: 'no-store',
      signal: AbortSignal.timeout(195000)
    });
  } catch {
    throw new Error('Local broker unavailable or review timed out. No new approval was issued.');
  }
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || 'The operation failed closed.');
  return result;
}
function invalidate() {
  generation++;
  preview = null;
  $('output').hidden = true;
  $('output').textContent = '';
  $('emptyPreview').hidden = false;
  $('releaseConsent').checked = false;
  $('releaseConsent').disabled = true;
  $('publish').disabled = true;
  $('previewState').textContent = 'Nothing released';
  $('reviewSummary').textContent = '';
}
function clearSensitive() {
  $('balance').value = '';
  $('selection').value = '';
}
function enable() {
  $('review').disabled = busy || !current || current.status !== 'pending' || !$('scopeConsent').checked;
  $('capture').disabled = busy || !source || !current || current.status !== 'pending';
  for (const id of ['balance','fees','buffer','selection','scopeConsent']) {
    $(id).disabled = busy || !current || current.status !== 'pending';
  }
  $('revoke').disabled = busy || !current;
  $('publish').disabled = busy || !preview || !$('releaseConsent').checked || Date.now()/1000 >= preview.review_until;
  for (const id of ['requests','create','refresh','saveKey']) $(id).disabled = busy;
}
function updateStatus() {
  if (!current) return;
  $('taskStatus').textContent = `Request ${current.id} · ${current.status}`;
  const option = [...$('requests').options].find(o => o.value === current.id);
  if (option) option.textContent = `${current.task.kind} · ${current.task.origin} · ${current.status}`;
}
function showTask() {
  invalidate(); clearSensitive();
  current = requests.find(r => r.id === $('requests').value) || null;
  $('taskDetails').hidden = !current;
  $('scopeConsent').checked = false;
  const funds = !current || current.task.kind === 'funds_check';
  $('fundsFields').hidden = !funds; $('textFields').hidden = funds;
  if (current) {
    $('taskOrigin').textContent = current.task.origin;
    $('taskPurpose').textContent = current.task.purpose;
    $('taskTtl').textContent = `${current.task.ttl_seconds} seconds after release`;
    $('taskKind').textContent = funds ? `Balance predicate for $${(current.task.parameters.amount_cents/100).toFixed(2)}` : 'Relevant, redacted excerpts';
    $('taskStatus').textContent = `Request ${current.id} · ${current.status}`;
    if (source && source.origin !== current.task.origin) message('This request targets another origin. Open that website, highlight the evidence and click AgentGate there.', true);
  }
  enable();
}
async function refresh(selectId = null) {
  const old = selectId || $('requests').value;
  const health = await api('health');
  $('reviewerMode').textContent = health.reviewer === 'ollama'
    ? `Independent local AI configured: ${health.model}. Review failures block release.`
    : 'MANUAL MODE: No independent AI is running. Pattern filtering and your explicit review are required.';
  $('reviewerMode').classList.toggle('manual', health.reviewer !== 'ollama');
  const data = await api('requests');
  requests = data.requests;
  $('requests').replaceChildren();
  if (!requests.length) $('requests').append(new Option('No requests. Create a test request or ask your assistant.', ''));
  for (const r of requests) $('requests').append(new Option(`${r.task.kind} · ${r.task.origin} · ${r.status}`, r.id));
  if (requests.some(r => r.id === old)) $('requests').value = old;
  showTask();
}
async function run(fn) {
  if (busy) return;
  busy = true; enable();
  try { await fn(); } catch (e) { message(e.message, true); }
  finally { busy = false; enable(); }
}
$('saveKey').addEventListener('click', () => run(async () => {
  const candidate = $('deviceKey').value.trim();
  if (!/^[A-Za-z0-9_-]{40,100}$/.test(candidate)) throw new Error('Paste the device key generated by broker.setup.');
  key = candidate;
  await api('health');
  await chrome.storage.local.set({ deviceKey: key });
  $('deviceKey').value = '';
  $('pairing').open = false;
  await refresh(); message('Paired with the local broker.');
}));
$('refresh').addEventListener('click', () => run(() => refresh()));
$('requests').addEventListener('change', showTask);
$('create').addEventListener('click', () => run(async () => {
  if (!source) throw new Error('Click the AgentGate toolbar button on the source website first.');
  const kind = $('kind').value;
  const parameters = kind === 'funds_check' ? { amount_cents: parseUsd($('amount').value), currency: 'USD' } : {};
  const result = await api('requests', { kind, origin: source.origin, purpose: $('purpose').value,
                                       ttl_seconds: Number($('ttl').value), parameters });
  await refresh(result.id); message('Request created. Verify its scope before preparing the answer.');
}));
$('capture').addEventListener('click', () => run(async () => {
  invalidate();
  if (!current) throw new Error('Select a request first.');
  if (source.origin !== current.task.origin) throw new Error('Source origin does not match this request.');
  const result = await chrome.runtime.sendMessage({ type: 'capture' });
  if (!result?.ok) throw new Error(result?.error || 'Capture failed.');
  if (result.origin !== current.task.origin) throw new Error('Source origin changed.');
  if (current.task.kind === 'funds_check') {
    parseUsd(result.text, { allowNegative: true });
    $('balance').value = result.text.trim();
    message('Captured one amount locally. Verify that it is the available balance for the intended account.');
  } else {
    $('selection').value = sanitizeText(result.text);
    message('Captured selected text and applied local pattern redaction. Review it for contextual private details.');
  }
}));
for (const id of ['balance','fees','buffer','selection']) $(id).addEventListener('input', () => { invalidate(); enable(); });
$('scopeConsent').addEventListener('change', enable);
$('releaseConsent').addEventListener('change', enable);
$('review').addEventListener('click', () => run(async () => {
  invalidate();
  if (!current || !source || source.origin !== current.task.origin) throw new Error('Bind the correct source website first.');
  if (!$('scopeConsent').checked) throw new Error('Confirm the source and task scope.');
  // Check origin again even for manually entered evidence. Manual evidence is labeled in docs.
  const tab = await chrome.tabs.get(source.tabId);
  if (normalizeOrigin(tab.url) !== current.task.origin) throw new Error('The source tab changed origin.');
  const ident = current.id;
  const myGeneration = generation;
  let payload;
  if (current.task.kind === 'funds_check') {
    payload = { origin: source.origin, candidate: fundsResult($('balance').value,
      current.task.parameters.amount_cents, $('fees').value, $('buffer').value) };
  } else {
    payload = { origin: source.origin, selection: sanitizeText($('selection').value) };
  }
  clearSensitive();
  message('The local privacy gate is reviewing the proposed answer.');
  const result = await api('review/' + ident, payload);
  if (myGeneration !== generation || current.id !== ident) throw new Error('Inputs changed during review. Revoke this request and start a new one.');
  preview = result;
  $('output').textContent = JSON.stringify(result.candidate, null, 2);
  $('output').hidden = false; $('emptyPreview').hidden = true;
  $('releaseConsent').disabled = false;
  $('previewState').textContent = 'Awaiting your approval';
  $('reviewSummary').textContent = result.mode === 'ollama'
    ? 'Local AI approved the candidate. Confirm the exact output below. Preview expires in 90 seconds.'
    : 'Manual review mode: no AI check was performed. Inspect the exact candidate carefully.';
  current.status = 'reviewed'; updateStatus();
  message('Review prepared. Nothing has been released to the assistant.');
}));
$('publish').addEventListener('click', () => run(async () => {
  if (!preview || !$('releaseConsent').checked) throw new Error('Review and approve the exact output first.');
  const result = await api('publish/' + current.id, { receipt: preview.receipt, digest: preview.digest });
  current.status = 'ready'; current.expires_at = result.expires_at; updateStatus();
  preview = null;
  $('releaseConsent').disabled = true; $('releaseConsent').checked = false;
  $('previewState').textContent = 'Released';
  $('reviewSummary').textContent = `Retrieval expires at ${new Date(result.expires_at*1000).toLocaleTimeString()}. The website remains signed in.`;
  message('Only the displayed answer is now available to the connected assistant.');
}));
$('revoke').addEventListener('click', () => run(async () => {
  if (!current) return;
  await api('revoke/' + current.id, {});
  invalidate(); clearSensitive(); await refresh();
  message('Request revoked. The broker will reject further retrieval.');
}));
setInterval(() => {
  if (preview && Date.now()/1000 >= preview.review_until) { invalidate(); message('The preview expired. Revoke this request and create a fresh one.', true); }
  if (current?.status === 'ready' && Date.now()/1000 >= current.expires_at) {
    invalidate(); current.status = 'expired'; updateStatus(); $('previewState').textContent = 'Expired';
    message('The retrieval lease expired. Previously received answers cannot be recalled.');
  }
  enable();
}, 1000);
window.addEventListener('pagehide', () => { clearSensitive(); preview = null; });

await chrome.storage.local.setAccessLevel({ accessLevel: 'TRUSTED_CONTEXTS' });
await chrome.storage.session.setAccessLevel({ accessLevel: 'TRUSTED_CONTEXTS' });
({ source } = await chrome.storage.session.get('source'));
source ??= null;
key = (await chrome.storage.local.get('deviceKey')).deviceKey || '';
$('extensionId').value = chrome.runtime.id;
$('sourceOrigin').textContent = source?.origin || 'No source selected';
$('pairing').open = !key;
if (key) await run(() => refresh());
else enable();
