import test from 'node:test';
import assert from 'node:assert/strict';
import {Connectors} from '../src/connectors.mjs';
import {canonical,b64url} from '../shared/protocol.mjs';
class Memory { items=new Map(); async get(k){return structuredClone(this.items.get(k));} async put(k,v){this.items.set(k,structuredClone(v));} async list({prefix}){return new Map([...this.items].filter(([k])=>k.startsWith(prefix)));} }
async function fixture(){const db=new Memory(),pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const {kty,crv,x,y}=await crypto.subtle.exportKey('jwk',pair.publicKey);await db.put('phone',{kty,crv,x,y});let now=1000000;const connectors=new Connectors(db,()=>now);const sign=async c=>({challenge:c,signature:b64url(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},pair.privateKey,new TextEncoder().encode(canonical(c))))});return {connectors,sign,advance:ms=>now+=ms};}
const auth={clientId:'test-client',redirectUri:'https://chat.example/callback',scope:['browser:delegate','offline_access'],codeChallenge:'a'.repeat(43),codeChallengeMethod:'S256',resource:'https://gate.example/mcp'};
test('a connector cannot access browser sessions until phone approval and OAuth completion',async()=>{const f=await fixture(),item=await f.connectors.create(auth,'Test assistant','handle');await assert.rejects(f.connectors.allowed(item.id));await assert.rejects(f.connectors.claim(item.id));await f.connectors.approve(item.id,await f.sign(item.challenge));await assert.rejects(f.connectors.allowed(item.id));await f.connectors.claim(item.id);await f.connectors.connected(item.id);await f.connectors.allowed(item.id);});
test('phone consent binds exact client, return URI, resource and scope',async()=>{const f=await fixture(),item=await f.connectors.create(auth,'Test assistant','handle');for(const edit of [{redirect_uri:'https://evil.example'},{client_id:'other-client'},{scope:['admin']},{resource:'https://other.example/mcp'}])await assert.rejects(f.connectors.approve(item.id,await f.sign({...item.challenge,...edit})));assert.equal((await f.connectors.get(item.id)).status,'requested');});
test('revocation blocks a completed connector and prevents reuse of old approval',async()=>{const f=await fixture(),item=await f.connectors.create(auth,'Test','handle'),receipt=await f.sign(item.challenge);await f.connectors.approve(item.id,receipt);await f.connectors.claim(item.id);await f.connectors.connected(item.id);await f.connectors.revoke(item.id);await assert.rejects(f.connectors.allowed(item.id));await assert.rejects(f.connectors.approve(item.id,receipt));});
test('expired OAuth consent cannot be exchanged and unsupported PKCE/scopes are refused',async()=>{const f=await fixture();await assert.rejects(f.connectors.create({...auth,codeChallengeMethod:'plain'},'Test','handle'));await assert.rejects(f.connectors.create({...auth,scope:['admin']},'Test','handle'));const item=await f.connectors.create(auth,'Test','handle');f.advance(600001);await assert.rejects(f.connectors.approve(item.id,await f.sign(item.challenge)));assert.equal((await f.connectors.get(item.id)).status,'expired');});
